application: yelp-love-175018
module: default
version: 1-0-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app
  secure: always
- url: /keys/?.*
  script: main.app
  login: admin
  secure: always
- url: /subscriptions/?.*
  script: main.app
  login: admin
  secure: always
- url: /aliases/?.*
  script: main.app
  login: admin
  secure: always
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
- url: /static
  static_dir: static
  secure: always
- url: /_themes/(.*)/img/(.*)
  static_files: themes/\1/static/img/\2
  upload: themes/(.*)/static/img/(.*)
  secure: always
  login: optional
- url: .* # Anything not explicitly listed above
  script: main.app
  login: required
  secure: always

builtins:
- remote_api: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^YelpLove.egg-info(/.*)?$
- ^config-example.py$
- ^google_appengine(/.*)?$
- ^tmp(/.*)?$
- ^virtualenv_.*$
