service: default
runtime: python311
app_engine_apis: true

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
- url: /static
  static_dir: static
  secure: always
